name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-8-jdk \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake libffi-dev libssl-dev \
          build-essential ccache m4 libc6-dev \
          libgmp-dev libmpfr-dev libmpc-dev \
          libssl-dev libffi-dev

    - name: Cache buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - name: Cache buildozer directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer kivy python-for-android cython faker

    - name: Build with Buildozer
      run: |
        export BUILDOZER_LOG_LEVEL=2
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: phonebook-generator-apk
        path: bin/*.apk

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Phonebook Generator v${{ github.run_number }}
        body: |
          Автоматически собранная версия генератора телефонной книги.
          
          ## Возможности:
          - Генерация контактов с уникальными ID
          - Поддержка кириллицы и латиницы
          - Настройка формата имен
          - Экспорт в CSV
          
          ## Установка:
          1. Скачайте APK файл
          2. Разрешите установку из неизвестных источников
          3. Установите приложение
        files: bin/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}